### PR TITLE
Feature | 578 | 274 | Parse issue numbers and move them to a status after merging a pr

### PR DESCRIPTION
**Pull request by dylanflint07**
Fixes TheRecruitLab/the-lab#578
Fixes TheRecruitLab/landing-pages#274

Blocked by #10, #11

Additions:

- Added capability to update the status of issue numbers after a merge

Demo
https://www.loom.com/share/d0e7017dd8ea4896a459c9a40fe0a2fd?sid=3354489a-03c8-4b4b-99f5-60276d2fef1f

### CODE REVIEW

**Comment by dylanflint07** [comment]
This is ready for review.

**Comment by dylanflint07** [comment]
@CdrMarks @weseldridge

**Comment by dylanflint07** [comment]
Please Review #13 first. This is blocked by it.

**Review by CdrMarks — APPROVED** [review]

**Comment by dylanflint07** [comment]
Closing since this has been moved into https://github.com/TheRecruitLab/issue-bot/pull/16

**Pull request closed without merging**
