### PR TITLE
Feature | 10 | 11 | Create pr when not in sync and Add commit messages to pr

### LINKED ISSUE #10: Create GitHub action for parsing issue numbers from commits and adding to PR description
**Acceptance Criteria**
* A workflow runs when a PR from source branch -> target branch is created or has commits added to it.

### LINKED ISSUE #11: Create PR when two branch are not in sync
User Story

As a developer, when I merge a new PR to dev, it should create a new PR for dev -> staging if none exists.

As a developer, when I merge a new PR to staging, it should create a new PR for staging -> production if none exists.

As a developer, when I merge dev -> staging, all the issues associated with the PR's commits in the PRs commits should move their status to staging.

As a developer, when I merge staging -> production, all the issues associated with the PR's commits should move their status to production and be closed.

**Acceptance Criteria**
* A PR is created when a non-empty diff can be generated between a source and target branch if a PR doesn't already exist.

### PR DESCRIPTION
**Pull request by dylanflint07**
Fixes #10
Fixes #11 

Additions:

- Added handle-branch-prs action

Modifications:

- Adjusted build structure to support multiple github actions

Demo:
https://www.loom.com/share/cb0f8c34438c42589d3268045fbeade2?sid=ce67e23d-f435-4694-a33f-bc86a2015ff0

### CODE REVIEW

**Comment by dylanflint07** [comment]
This is ready for review. @CdrMarks @weseldridge

**Comment by CdrMarks** [comment]
This seems to work really well.

I wonder if it's possible to add the PR that was created to the [Engineering project](https://github.com/orgs/TheRecruitLab/projects/2)?  My goal is to see these PRs on the [Releases View](https://github.com/orgs/TheRecruitLab/projects/2/views/8).

**Comment by dylanflint07** [comment]
@CdrMarks We might be able to. I'm not sure. It's filtering for prs and the other boards aren't, so I'd have to look and see what exactly we need to do to get it to show up only on the releases view.

Do you want to make a separate issue and I can follow up on it once we get all the other workflows connected?

**Comment by CdrMarks** [comment]
The view is already configured to show only PRs that are in status Dev or Staging.

If you can perform two steps when creating the PR, I think we'll be set:
* Add to the [Engineering project](https://github.com/orgs/TheRecruitLab/projects/2)
* Set the Status to match the source branch name.

**Comment by dylanflint07** [comment]
Okay. I'll start working on that and add it to this PR.

**Comment by dylanflint07** [comment]
@CdrMarks Actually I think it'll be less of a headache if I just merge the 3 PRs together into one feature PR and then add it. Otherwise, there are going to be a lot of merge conflicts to deal with.

I'm going to close this and then create a new PR for all of them.

**Comment by dylanflint07** [comment]
Closing since this has been moved into https://github.com/TheRecruitLab/issue-bot/pull/16

**Pull request closed without merging**
